# Generated by Django 4.0.1 on 2022-02-22 10:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_alter_emailsettings_email_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailsettings',
            name='email_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 22, 10, 14, 33, 170051, tzinfo=utc)),
        ),
    ]
