# Generated by Django 4.0.1 on 2022-02-22 10:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_alter_emailsettings_email_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailsettings',
            name='email_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
