# Generated by Django 4.0.1 on 2022-02-22 17:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_alter_emailsettings_email_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailsettings',
            name='email_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='emailsettings',
            name='email_time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
